/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.ipp.zapt

#include <clusters/FaultInjection/Commands.h>

#include <app/data-model/Decode.h>
#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FaultInjection {
namespace Commands {
namespace FailAtFault {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kType), type);
    encoder.Encode(to_underlying(Fields::kId), id);
    encoder.Encode(to_underlying(Fields::kNumCallsToSkip), numCallsToSkip);
    encoder.Encode(to_underlying(Fields::kNumCallsToFail), numCallsToFail);
    encoder.Encode(to_underlying(Fields::kTakeMutex), takeMutex);
    encoder.Encode(to_underlying(Fields::kTargetEndpoint), targetEndpoint);
    encoder.Encode(to_underlying(Fields::kTargetCluster), targetCluster);
    encoder.Encode(to_underlying(Fields::kTargetId), targetId);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        VerifyOrReturnError(err != CHIP_ERROR_END_OF_TLV, CHIP_NO_ERROR);
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kType))
        {
            err = DataModel::Decode(reader, type);
        }
        else if (__context_tag == to_underlying(Fields::kId))
        {
            err = DataModel::Decode(reader, id);
        }
        else if (__context_tag == to_underlying(Fields::kNumCallsToSkip))
        {
            err = DataModel::Decode(reader, numCallsToSkip);
        }
        else if (__context_tag == to_underlying(Fields::kNumCallsToFail))
        {
            err = DataModel::Decode(reader, numCallsToFail);
        }
        else if (__context_tag == to_underlying(Fields::kTakeMutex))
        {
            err = DataModel::Decode(reader, takeMutex);
        }
        else if (__context_tag == to_underlying(Fields::kTargetEndpoint))
        {
            err = DataModel::Decode(reader, targetEndpoint);
        }
        else if (__context_tag == to_underlying(Fields::kTargetCluster))
        {
            err = DataModel::Decode(reader, targetCluster);
        }
        else if (__context_tag == to_underlying(Fields::kTargetId))
        {
            err = DataModel::Decode(reader, targetId);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace FailAtFault.
namespace FailRandomlyAtFault {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kType), type);
    encoder.Encode(to_underlying(Fields::kId), id);
    encoder.Encode(to_underlying(Fields::kPercentage), percentage);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        VerifyOrReturnError(err != CHIP_ERROR_END_OF_TLV, CHIP_NO_ERROR);
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kType))
        {
            err = DataModel::Decode(reader, type);
        }
        else if (__context_tag == to_underlying(Fields::kId))
        {
            err = DataModel::Decode(reader, id);
        }
        else if (__context_tag == to_underlying(Fields::kPercentage))
        {
            err = DataModel::Decode(reader, percentage);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace FailRandomlyAtFault.
} // namespace Commands
} // namespace FaultInjection
} // namespace Clusters
} // namespace app
} // namespace chip
